#
#####################################################
#          ,--,                                   
#        ,--.'|      ,----,             ,---,     
#     ,--,  | :    .'   .' \          ,--.' |     
#  ,---.'|  : '  ,----,'    |         |  |  :     
#  ;   : |  | ;  |    :  .  ;.--.--.  :  :  :     
#  |   | : _' |  ;    |.'  //  /    ' :  |  |,--. 
#  :   : |.'  |  `----'/  ;|  :  /`./ |  :  '   | 
#  |   ' '  ; :    /  ;  / |  :  ;_   |  |   /' : 
#  \   \  .'. |   ;  /  /-, \  \    `.'  :  | | | 
#   `---`:  | '  /  /  /.`|  `----.   \  |  ' | : 
#        '  ; |./__;      : /  /`--'  /  :  :_:,' 
#        |  : ;|   :    .' '--'.     /|  | ,'     
#        '  ,/ ;   | .'      `--'---' `--''       
#        '--'  `---'                              
############Continuous integration build config####

image: opensuse:tumbleweed

pipelines:
    default:
    - step:
        script:
         - zypper update --non-interactive
         - zypper install --non-interactive tcsh 
         - ./mouli.sh